const horz_chart_data = [
  {
    number_of_sub_tasks: "22",
    story_name: "Adding Tested APIs into BOB as Bricks",
    project_id: "10234",
    completed_sub_tasks: "7",
    story_id: "74342",
    progress_percentage: "31",
    sprint_id: "683",
  },
  {
    number_of_sub_tasks: "5",
    story_name: "CANVAS UI and Functionalities",
    project_id: "10235",
    completed_sub_tasks: "0",
    story_id: "75203",
    progress_percentage: "0",
    sprint_id: "688",
  },
  {
    number_of_sub_tasks: "4",
    story_name: "Anchor App UI Creation ",
    project_id: "10235",
    completed_sub_tasks: "0",
    story_id: "74601",
    progress_percentage: "0",
    sprint_id: "688",
  },
  {
    number_of_sub_tasks: "5",
    story_name:
      "Replace the api calls to third party engagement channel api’s in the channel services to use Bob workflows",
    project_id: "10234",
    completed_sub_tasks: "1",
    story_id: "74344",
    progress_percentage: "20",
    sprint_id: "683",
  },
  {
    number_of_sub_tasks: "8",
    story_name: "Merging from Monet 1.0 to 2.0",
    project_id: "10235",
    completed_sub_tasks: "2",
    story_id: "74598",
    progress_percentage: "25",
    sprint_id: "688",
  },
  {
    number_of_sub_tasks: "44",
    story_name: "Workflow creation and testing for each brick",
    project_id: "10234",
    completed_sub_tasks: "13",
    story_id: "74343",
    progress_percentage: "29",
    sprint_id: "683",
  },
  {
    number_of_sub_tasks: "7",
    story_name:
      "Refactor channel services  to just handle the content resolution consolidating into a single microservice",
    project_id: "10234",
    completed_sub_tasks: "3",
    story_id: "74345",
    progress_percentage: "42",
    sprint_id: "683",
  },
  {
    number_of_sub_tasks: "4",
    story_name: "Mobius API to Partner API reconciliation",
    project_id: "10234",
    completed_sub_tasks: "1",
    story_id: "74386",
    progress_percentage: "25",
    sprint_id: "683",
  },
  {
    number_of_sub_tasks: "9",
    story_name: "Sea Tunnel Sub Process",
    project_id: "10234",
    completed_sub_tasks: "3",
    story_id: "74354",
    progress_percentage: "33",
    sprint_id: "683",
  },
  {
    number_of_sub_tasks: "15",
    story_name: "End to End business use Case - Weather data",
    project_id: "10234",
    completed_sub_tasks: "5",
    story_id: "74387",
    progress_percentage: "33",
    sprint_id: "683",
  },
  {
    number_of_sub_tasks: "5",
    story_name: "Content Type Evaluation",
    project_id: "10234",
    completed_sub_tasks: "1",
    story_id: "74385",
    progress_percentage: "20",
    sprint_id: "683",
  },
  {
    number_of_sub_tasks: "3",
    story_name: "GrapeJS styles R&D ",
    project_id: "10235",
    completed_sub_tasks: "0",
    story_id: "75278",
    progress_percentage: "0",
    sprint_id: "688",
  },
  {
    number_of_sub_tasks: "8",
    story_name: "Streamlining Panels (Left, Right, Bottom) ",
    project_id: "10235",
    completed_sub_tasks: "1",
    story_id: "74599",
    progress_percentage: "12",
    sprint_id: "688",
  },
  {
    number_of_sub_tasks: "6",
    story_name: "Experience page in Monet 2.0",
    project_id: "10235",
    completed_sub_tasks: "0",
    story_id: "74619",
    progress_percentage: "0",
    sprint_id: "688",
  },
  {
    number_of_sub_tasks: "10",
    story_name: "End to End story for Bitcoin",
    project_id: "10234",
    completed_sub_tasks: "6",
    story_id: "75806",
    progress_percentage: "60",
    sprint_id: "683",
  },
  {
    number_of_sub_tasks: "22",
    story_name: "Identification and testing of all 3rd party APIs",
    project_id: "10234",
    completed_sub_tasks: "11",
    story_id: "74341",
    progress_percentage: "50",
    sprint_id: "683",
  },
];

export default horz_chart_data;
