const time_log = [
  {
    remaining_estimate: "0m",
    original_estimate: "0m",
    project_id: "10234",
    story_id: "74344",
    sprint_id: "683",
    time_spent: "Not added",
  },
  {
    remaining_estimate: "Not added",
    original_estimate: "Not added",
    project_id: "10234",
    story_id: "74386",
    sprint_id: "683",
    time_spent: "Not added",
  },
  {
    remaining_estimate: "Not added",
    original_estimate: "Not added",
    project_id: "10234",
    story_id: "74387",
    sprint_id: "683",
    time_spent: "Not added",
  },
  {
    remaining_estimate: "Not added",
    original_estimate: "Not added",
    project_id: "10234",
    story_id: "74343",
    sprint_id: "683",
    time_spent: "Not added",
  },
  {
    remaining_estimate: "Not added",
    original_estimate: "Not added",
    project_id: "10234",
    story_id: "74342",
    sprint_id: "683",
    time_spent: "Not added",
  },
  {
    remaining_estimate: "Not added",
    original_estimate: "Not added",
    project_id: "10234",
    story_id: "74385",
    sprint_id: "683",
    time_spent: "Not added",
  },
  {
    remaining_estimate: "Not added",
    original_estimate: "Not added",
    project_id: "10234",
    story_id: "74341",
    sprint_id: "683",
    time_spent: "Not added",
  },
  {
    remaining_estimate: "1w 3d",
    original_estimate: "1w 3d",
    project_id: "10234",
    story_id: "74345",
    sprint_id: "683",
    time_spent: "Not added",
  },
  {
    remaining_estimate: "Not added",
    original_estimate: "Not added",
    project_id: "10234",
    story_id: "75806",
    sprint_id: "683",
    time_spent: "Not added",
  },
  {
    remaining_estimate: "Not added",
    original_estimate: "Not added",
    project_id: "10234",
    story_id: "74354",
    sprint_id: "683",
    time_spent: "Not added",
  },
  {
    remaining_estimate: "0m",
    original_estimate: "Not added",
    project_id: "10235",
    story_id: "75278",
    sprint_id: "688",
    time_spent: "1w",
  },
  {
    remaining_estimate: "Not added",
    original_estimate: "Not added",
    project_id: "10235",
    story_id: "74601",
    sprint_id: "688",
    time_spent: "Not added",
  },
  {
    remaining_estimate: "0m",
    original_estimate: "Not added",
    project_id: "10235",
    story_id: "75203",
    sprint_id: "688",
    time_spent: "1w",
  },
  {
    remaining_estimate: "0m",
    original_estimate: "Not added",
    project_id: "10235",
    story_id: "74599",
    sprint_id: "688",
    time_spent: "2w",
  },
  {
    remaining_estimate: "0m",
    original_estimate: "Not added",
    project_id: "10235",
    story_id: "74598",
    sprint_id: "688",
    time_spent: "1w",
  },
  {
    remaining_estimate: "0m",
    original_estimate: "Not added",
    project_id: "10235",
    story_id: "74619",
    sprint_id: "688",
    time_spent: "1w",
  },
];

export default time_log;
